### ISSUE TITLE
Update Datastore indexes

### ISSUE THREAD

**Issue by yuri-sergiichuk** [SpineEventEngine/gcloud-java#167]
The current indexes config in the repository is outdated and does not work anymore with the Spine 2.x version of the library.

At least the following index should be added:

```yaml

  - kind: spine.server.aggregate.AggregateEventRecord
    properties:
      - name: aggregate_id
      - name: version
        direction: desc
      - name: created
        direction: desc

```

We should also check if the currently defined indexes are still relevant.

**Comment by MykytaPimonovTD** [comment]
For Spine `1.9.1`, the correct configuration for the aggregate is as follows:

```yaml
  - kind: purchases.Product
    properties:
      - name: aggregate_id
      - name: version
        direction: desc
      - name: created
        direction: desc
      - name: snapshot
```
